site:
  title: Data Catalog
  start_page: data-catalog:data-catalog:uuidea_Data_Catalog.adoc
content:
  sources: 
  - url: http://data-catalog.uuidea.eu
    branches: main
    start_page: data-catalog:data-catalog:uuidea_Data_Catalog.adoc
    
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: supplemental-ui  

asciidoc:
  attributes:
    page-pagination: ''
    experimental: ''
    kroki-fetch-diagram: true # Render images in browser. Makes building much faster which is convenient for local development.
    kroki-default-format: svg@
    kroki-server-url: http://kroki.uuidea.eu:8000/ 
  extensions:
    - asciidoctor-kroki
    - '@djencks/asciidoctor-mathjax'

    # - asciidoctor-mermaid # Add this line to enable Mermaid support

output:
  clean: true
  dir: ./docs

antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
    - require: '@sntke/antora-mermaid-extension' # <1>
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
      script_stem: header-scripts # <3>
      mermaid_initialize_options: # <4>
        start_on_load: true 